// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVBjhK5rBxotAkKQXYSEeovjLdVP5AFW8',
    appId: '1:832271984905:web:ae3edcaa1348aa9c980bd8',
    messagingSenderId: '832271984905',
    projectId: 'cattle-plus',
    authDomain: 'cattle-plus.firebaseapp.com',
    storageBucket: 'cattle-plus.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXP3X-CeuF_qdFX20WY0AXWjRvztp4Mhw',
    appId: '1:832271984905:android:247e076945c73cca980bd8',
    messagingSenderId: '832271984905',
    projectId: 'cattle-plus',
    storageBucket: 'cattle-plus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABHPvSX-4D8CsDwNsPHQ8vBI5EsC9-Hyk',
    appId: '1:832271984905:ios:84aef9fdec740177980bd8',
    messagingSenderId: '832271984905',
    projectId: 'cattle-plus',
    storageBucket: 'cattle-plus.appspot.com',
    iosClientId: '832271984905-966s4cgjbiqnqc520d14pio3s3p5halv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cattleplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABHPvSX-4D8CsDwNsPHQ8vBI5EsC9-Hyk',
    appId: '1:832271984905:ios:a0a73a83ddbab9e9980bd8',
    messagingSenderId: '832271984905',
    projectId: 'cattle-plus',
    storageBucket: 'cattle-plus.appspot.com',
    iosClientId: '832271984905-m1hcie4dolvo8b5d0e0do1va7ltreusu.apps.googleusercontent.com',
    iosBundleId: 'com.example.cattleplus.RunnerTests',
  );
}
